spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
  application:
    name: SHIPMENT_SERVICE
  profiles:
    active:
      - dev
      - dev-local
  liquibase:
    change-log: classpath:db/master.xml
server:
  port: 8081
logging:
  level:
    sql: debug