spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
  application:
    name: SHIPMENT_SERVICE
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:shop_sport
    username: sa
    password: password
  liquibase:
    change-log: classpath:db/master-test.xml
server:
  port: 8081
logging:
  level:
    sql: debug