spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
  application:
    name: SHIPMENT_SERVICE
  profiles:
    active:
      - dev
      - dev-local
  datasource:
    url: jdbc:h2:mem:shop_sport
    username: sa
    password: password
  liquibase:
    change-log: classpath:db/master-test.xml
server:
  port: 8081
logging:
  level:
    sql: debug